In [1]:
from pathlib import Path
import sys

import pandas as pd

# Add project root to Python path
PROJECT_ROOT = Path.cwd().parent
sys.path.append(str(PROJECT_ROOT))

from src.data.loader import (
    load_phishing_data,
    load_legitimate_data,
    sample_phishing_urls,
    sample_legitimate_urls,
)

In [ ]:
import requests
from pathlib import Path

url = "http://data.phishtank.com/data/online-valid.csv"

output_path = Path("../data/raw/online-valid.csv")

response = requests.get(url, timeout=30)

response.raise_for_status()

output_path.parent.mkdir(parents=True, exist_ok=True)

with open(output_path, "wb") as f:
    f.write(response.content)

print(f"Downloaded successfully: {output_path}")

In [2]:
import sys
from pathlib import Path

PROJECT_ROOT = Path.cwd().parent
sys.path.insert(0, str(PROJECT_ROOT))

In [3]:
PHISHING_DATA_PATH = PROJECT_ROOT / "data" / "raw" / "2.online-valid.csv"
LEGITIMATE_DATA_PATH = PROJECT_ROOT / "data" / "raw" / "1.Benign_list_big_final.csv"

print(f"Phishing dataset : {PHISHING_DATA_PATH}")
print(f"Legitimate dataset : {LEGITIMATE_DATA_PATH}")

Phishing dataset : c:\Users\nk134\OneDrive\Desktop\coding\phishguard-x\data\raw\2.online-valid.csv
Legitimate dataset : c:\Users\nk134\OneDrive\Desktop\coding\phishguard-x\data\raw\1.Benign_list_big_final.csv

In [4]:
# Loading the phishing URLs dataset

data0 = load_phishing_data(PHISHING_DATA_PATH)

data0.head()

,phish_id,url,phish_detail_url,submission_time,verified,verification_time,online,target
0,9521570,https://centrala-administracja.vercel.app/,http://www.phishtank.com/phish_detail.php?phis...,2026-09-09T18:17:37+00:00,yes,2026-09-09T18:21:54+00:00,yes,Other
1,9521566,https://mawnowvasnanz-dpleh6oql3aj.edgeone.dev/,http://www.phishtank.com/phish_detail.php?phis...,2026-09-09T18:10:46+00:00,yes,2026-09-09T18:21:54+00:00,yes,Microsoft
2,9521565,https://login-outlook365.yzz.me/,http://www.phishtank.com/phish_detail.php?phis...,2026-09-09T18:07:34+00:00,yes,2026-09-09T18:11:54+00:00,yes,Microsoft
3,9521564,https://login-outlook365.yzz.me/?i=1,http://www.phishtank.com/phish_detail.php?phis...,2026-09-09T18:07:13+00:00,yes,2026-09-09T18:11:54+00:00,yes,Microsoft
4,9521563,https://fb-meta-verified-14259.vercel.app/,http://www.phishtank.com/phish_detail.php?phis...,2026-09-09T18:01:51+00:00,yes,2026-09-09T18:11:54+00:00,yes,Facebook

In [5]:
data0.shape

(75472, 8)

In [6]:
phishurl = data0.sample(n = 5000, random_state = 12).copy()
phishurl = phishurl.reset_index(drop=True)
phishurl.head()

,phish_id,url,phish_detail_url,submission_time,verified,verification_time,online,target
0,9475335,https://chrtrer09765.framer.website/,http://www.phishtank.com/phish_detail.php?phis...,2026-07-11T18:27:29+00:00,yes,2026-07-11T18:52:38+00:00,yes,Other
1,9491283,https://full-transportation-630661.framer.app/,http://www.phishtank.com/phish_detail.php?phis...,2026-07-30T13:57:34+00:00,yes,2026-07-30T14:03:21+00:00,yes,Other
2,7560847,https://domappcheckomeg7.firebaseapp.com/,http://www.phishtank.com/phish_detail.php?phis...,2022-06-21T00:08:33+00:00,yes,2022-06-21T00:12:56+00:00,yes,Other
3,9400443,https://belproxskyfqa.weebly.com/,http://www.phishtank.com/phish_detail.php?phis...,2026-04-21T22:51:03+00:00,yes,2026-04-21T23:03:12+00:00,yes,Other
4,9437465,https://www.gov-parkingqs.cyou/com,http://www.phishtank.com/phish_detail.php?phis...,2026-05-29T04:00:10+00:00,yes,2026-05-29T04:22:19+00:00,yes,Other

In [7]:
phishurl.shape

(5000, 8)

In [8]:

data1 = pd.read_csv(LEGITIMATE_DATA_PATH)
data1.columns = ['URLs']
data1.head()

                                                URLs
0  http://1337x.to/torrent/1110018/Blackhat-2015-...
1  http://1337x.to/torrent/1122940/Blackhat-2015-...
2  http://1337x.to/torrent/1124395/Fast-and-Furio...
3  http://1337x.to/torrent/1145504/Avengers-Age-o...
4  http://1337x.to/torrent/1160078/Avengers-age-o...

In [9]:
legiurl = data1.sample(n = 5000, random_state = 12).copy()
legiurl = legiurl.reset_index(drop=True)
legiurl.head()

                                                URLs
0  http://graphicriver.net/search?date=this-month...
1  http://ecnavi.jp/redirect/?url=http://www.cros...
2  https://hubpages.com/signin?explain=follow+Hub...
3  http://extratorrent.cc/torrent/4190536/AOMEI+B...
4  http://icicibank.com/Personal-Banking/offers/o...

In [10]:
legiurl.shape

(5000, 1)